json-ld for Company/Shareholders dataproduct
digitalliving/standards pull request #12
Opened 2020-08-26 10:54 UTC by samuelashraff

2020-08-26 13:18 UTC, joakimnordling commented on draft/DataProducts/Company/Shareholders.html
> +    <link rel="shortcut icon" href="https://fastapi.tiangolo.com/img/favicon.png" />
I don't really think our html versions should include a FastAPI shortcut icon/favicon. But all of the other HTML versions has this, so I think this will be OK for now, but we'd need to figure out a way to get rid of them easily for all of them. Please make sure there's a task added to take care of this.

2020-08-31 06:16 UTC, soderluk requested changes

2020-08-31 06:16 UTC, soderluk commented on draft/DataProducts/Company/Shareholders.jsonld
> +      "@prefix": false
`@prefix: false` isn't really needed. Only use it when it actually is a prefix.

2020-08-31 06:16 UTC, soderluk commented on draft/DataProducts/Company/Shareholders.jsonld
> +    "schema": {
Why's this named `schema`? When I see `schema`, I think of schema.org as a vocabulary. Maybe something that would describe the actual vocabulary that is used.

2020-08-31 06:16 UTC, soderluk commented on draft/DataProducts/Company/Shareholders.jsonld
> +    "share_class": {
Should we keep the camelCase instead of snake_case here?

2020-09-08 11:07 UTC, soderluk approved these changes

2020-09-08 11:18 UTC, joakimnordling commented on draft/DataProducts/Company/Shareholders.json
> +        "description": "The base model for the shareholders info request."
I don't think these lines about "model/base model" should be propagated from the code all the way to the openapi spec.

2020-09-08 11:23 UTC, joakimnordling requested changes
The comments about pydantic models should not be propagated to the OpenAPI spec.

2020-09-08 11:31 UTC, soderluk commented on draft/DataProducts/Company/Shareholders.json
> +        "description": "The base model for the shareholders info request."
Yeah, I took it from the productizer open api spec. Will just remove these.

2020-09-08 11:34 UTC, joakimnordling approved these changes
Looks OK to me.

2020-09-08 11:59 UTC, merged